project:
  published: true
  name: Macintosh 128K
  status: In progress
  start_date: "2021-04-23"
  thumbnail: img_001.jpg
  description:
    - "Repair job"
    - ""
    - "+ Downgrade Plus to 128K"
    - "+ Repair battery corrosion"
    - "+ Floppy drive refurbishment"
