project:
  published: true
  name: Sinclair ZX81 E
  manufacturer: Sinclair
  type: Computer
  status: In progress
  start_date: "2021-03-13"
  thumbnail: img_001.jpg
  description:
    - "Issue One / 2C184E ULA / Dual RAM ICs"
    - ""
    - "+ Bad keyboard membrane"
    - "+ Composite mod"