project:
  published: true
  name: Philips NMS 8220 MSX2
  status: On hold
  start_date: "2021-04-05"
  thumbnail: img_001.jpg
  description:
    - "MSX 2 computer"
    - ""
    - "+ Faulty inductor"
    - "+ Missing cover"
