project:
  published: true
  name: Commodore 1541 drive
  status: Completed
  start_date: "2021-02-12"
  thumbnail: img_001.jpg
  description:
    - "Alps mechanism / PCB: -"
    - ""
    - + Corroded ROM pins
