project:
  published: true
  name: Commodore 64
  manufacturer: Commodore
  type: Computer
  status: On hold
  start_date: "2021-02-12"
  thumbnail: img_001.jpg
  description:
    - "PCB version: 250425"
    - ""
    - "+ Bought as unknown / untested"
    - "+ C64 was working perfectly"
    - "+ 1541 drive faulty"
    - "+ Datacasette cover missing"
