project:
  published: true
  name: Commodore 64
  status: In progress
  start_date: "2021-02-14"
  thumbnail: IMG_20210214_193656.jpg
  description:
    - "Bought in unknown condition<br>"
    - ""
    - "- C64 was working perfectly"
    - "- 1541 drive faulty"
    - "- Datacasette cover missing"
