project:
  published: false
  name: Commodore 64
  status: In progress
  start_date: "2021-02-14"
  thumbnail: 
  description:
    - "Bought in unknown condition"
    - "+ C64 was working perfectly"
    - "+ 1541 drive faulty"
    - "+ Datacasette cover missing"
