project:
  published: true
  name: Sinclair QL
  status: In progress
  start_date: "2021-03-27"
  thumbnail: img_001.jpg
  description:
    - "Issue 7 PCB"
    - ""
    - "+ Faulty keyboard membrane"
