project:
  published: true
  name: Sinclair ZX81 B
  manufacturer: Sinclair
  type: Computer
  status: Completed
  start_date: "2021-03-13"
  thumbnail: img_011.jpg
  description:
    - "Issue 1 / 2C184E ULA / Single RAM IC"
    - ""
    - "+ Composite mod"
    - "+ Faulty Z80 CPU"
    - "+ Broken keyboard membrane"
    - "+ 16K ram upgrade"