project:
  published: true
  name: Macintosh II/ci
  manufacturer: Apple
  type: Computer
  status: In progress
  start_date: "2020-12-06"
  thumbnail: img_001.jpg
  description:
    - "* Capacitor replacement"
    - "* Upgrades"
