project:
  published: true
  name: Unisys UVT-1224
  status: On hold
  start_date: "2020-20-19"
  thumbnail: IMG_20201220_164903.jpg
  description:
    - "An interresting video terminal from the 80s"
