project:
  published: true
  name: Macintosh Classic II
  status: Completed
  start_date: "2021-05-01"
  thumbnail: img_013.jpg
  description: 
    - "Extremely clean computer"
    - ""
    - "- Capacitors replaced"
