project:
  published: true
  name: Commodore 1541c
  status: On hold
  start_date: "2021-02-23"
  thumbnail: img_001.jpg
  description:
    - "Newtronics mechanism / PCB 251854"
    - ""
    - "+ Dirty head"
    - "+ Homing problem"
