project:
  published: true
  name: Sinclair ZX81 video board
  manufacturer: Retro.Engineer
  type: Other
  status: Completed
  start_date: "2021-03-20"
  thumbnail: img_009.png
  description:
    - "Fixes the issue of using a ZX-81 with colour TVs"
    - ""
    - "+ Adds the 'back porch' to the composite video signal"
    - "+ Specfically designed for the 2C184E ULA"
