project:
  published: true
  name: Apple 12" RGB monitor (M1296)
  status: In progress
  start_date: "2021-02-15"
  thumbnail: IMG_20210218_104446.jpg
  description:
    - "Bought as faulty"
    - "Sync loss"
