project:
  published: true
  name: Apple 12" RGB monitor (M1296)
  status: Completed
  start_date: "2021-02-15"
  thumbnail: img_001.jpg
  description:
    - "Bought as faulty"
    - ""
    - "* Sync loss"
    - "* Bad capacitors"
    - "* Faulty resistor"
