project:
  published: true
  name: Sinclair ZX81 D
  status: Completed
  start_date: "2021-03-13"
  thumbnail: img_001.jpg
  description:
    - "Issue 3 / 2C184E ULA / Single RAM IC"
    - ""
    - "+ Composite upgrade"
    - "+ 16K ram upgrade"