project:
  published: true
  name: Commodore 64 breadbin B
  status: In progress
  start_date: "2021-02-22"
  thumbnail: img_001.jpg
  description:
  description:
    - "PCB version: 250425"
    - ""
    - "+ Bought as unknown / untested"
    - "+ Bad memory IC"