project:
  published: true
  name: Macintosh Color Classic
  status: In progress
  start_date: "2021-01-14"
  thumbnail: IMG_20210114_171328.jpg
  description:
    - "Baught as faulty, leaking capacitors, faulty keyboard"
