project:
  published: true
  name: Macintosh Color Classic
  status: In progress
  start_date: "2021-01-14"
  thumbnail: img_001.jpg
  description:
    - "Bought as faulty, leaking capacitors, faulty keyboard"
