project:
  published: true
  name: Tickle me Elmo (1996)
  status: On hold
  start_date: "2021-02-07"
  thumbnail: img_007.jpg
  description:
    - "An original 1996 model Tickle me Elmo with extensive battery leakage"
