project:
  published: true
  name: Sinclair ZX81 C
  manufacturer: Sinclair
  type: Computer
  status: In progress
  start_date: "2021-03-13"
  thumbnail: img_007.jpg
  description:
    - "Issue 1 / 2C210E ULA / Dual RAM ICs"
    - ""
    - "+ Faulty ULA replaced with vLA81"
    - "+ 16K ram upgrade"