project:
  published: true
  name: Apple 12" Monochrome monitor
  status: On hold
  start_date: "2020-12-06"
  thumbnail: img_001.jpg
  description:
    - "* Cracked solder joints"
    - "* Capacitor replacement"
