project:
  published: true
  name: Commodore 64 breadbin
  status: Completed
  start_date: "2021-02-21"
  thumbnail: img_001.jpg
  description:
    - "PCB version: 250407 rev A"
    - ""
    - "+ Bought as faulty / black screen"
    - "+ Bad SID chip"
    - "+ Bad CIA chip"
