project:
  published: true
  name: Commodore 1541 drive
  status: Completed
  start_date: "2021-02-23"
  thumbnail: img_001.jpg
  description:
    - Newtronics mechanism / Assy 250442
    - ""
    - + Low reset line 
    - + No ATN signal from C64
    - + No communication with C64
    - + Open circuit inside read / write head
