project:
  published: true
  name: Macintosh SE
  status: In progress
  start_date: "2020-20-30"
  last_update: "2021-01-09"
  thumbnail: IMG_20201223_112723.jpg
  description: 
    - "Very yellowed case needed a lot of cleaning. <br>"
    - ""
    - "- Replaced harddrive"
    - "- External battery modification"
    - "- De-yellowed"