project:
  published: true
  name: Macintosh SE
  status: Completed
  start_date: "2020-20-30"
  last_update: "2021-01-20"
  thumbnail: image-0001.jpg
  description: 
    - "Very yellowed case needed a lot of cleaning. <br>"
    - ""
    - "- Replaced harddrive"
    - "- External battery modification"
    - "- De-yellowed"
