project:
  published: true
  name: Macintosh 512K
  manufacturer: Apple
  type: Computer
  status: In progress
  start_date: "2021-04-23"
  thumbnail: img_001.jpg
  description:
    - "Repair job"
    - ""
    - "+ Replace bad capacitors"
    - "+ Floppy drive refurbishment"
