project:
  published: true
  name: Retro VFD clock
  status: On hold
  start_date: "2021-02-07"
  thumbnail: img_001.jpg
  description:
    - "Designing and building a clock using a Russian IV-18 VFD tube"
