project:
  published: true
  name: Macintosh Classic II
  status: In progress
  start_date: "2020-20-30"
  thumbnail: img_001.jpg
  description:
    - "Leaking capacitors caused damage on the main board"
