project:
  published: true
  name: Macintosh Classic II
  status: On hold
  start_date: "2020-20-30"
  thumbnail: IMG_20201223_105349.jpg
  description: 
    - "Leaking capacitors caused damage on the main board"
