project:
  published: true
  name: Sinclair ZX81 A
  manufacturer: Sinclair
  type: Computer
  status: Completed
  start_date: "2021-03-13"
  thumbnail: img_011.jpg
  description:
    - "Issue 1 / 2C184E ULA / Dual RAM ICs"
    - ""
    - "+ Composite mod"
    - "+ 16K ram upgrade"