project:
  published: true
  name: Sharp PC-1251
  status: On hold
  start_date: "2021-01-16"
  thumbnail: IMG_20210116_172207.jpg
  description:
    - "A very interresting portable micro computer, introduced in 1982"
