project:
  published: true
  name: Sharp PC-1251
  status: On hold
  start_date: "2021-01-16"
  thumbnail: img_003.jpg
  description:
    - "A very interresting portable micro computer, introduced in 1982"
