project:
  published: false
  name: Macintosh II/ci
  status: In progress
  start_date: "2021-04-10"
  thumbnail: img_009.jpg
  description:
    - "Repair job"
    - ""
    - "+ Full capacitor replacement"
    - "+ Floppy drive refurbishment"
